### PR TITLE
Implement missing packets

### PR DESCRIPTION
**Pull request by ivanbiljan**
At the time of writing (Sep 9th, 2020) 20 or so packets have been implemented. Things are still WIP and this PR should be used as a tracker to reduce the chance of duplicate work, should anyone else take this project up. I will commit new progress fairly regularly and intend to handle as many packets as I can. I will leave a comment once I feel like everything is ready for a full review/merge.

### CODE REVIEW

**Comment by kevzhao2** [comment]
Thanks so much for this! When I get them time to do so, I'll take a look at this. :)

**Comment by ivanbiljan** [comment]
Removed the [WIP] tag. Cca 45/50 have been implemented, however I wish to migrate to a better workflow since there are a few other things I'd like to work on (and the PR is already big as it is) before proceeding with packet implementations.

**Comment by ivanbiljan** [comment]
This pull request is now complete. Packets defined in 1.4.1 have been implemented as well, however no previous packet validation was performed (meaning I've not updated packets defined pre 1.4.1 to reflect changes the update might've introduced). I will leave this for another pull request if necessary.

**Comment by kevzhao2** [comment]
Thanks Ivan! I will start reviewing this and double checking for errors.

**Pull request closed without merging**
